//list
export const COMMANDS_LIST_REQUEST = "COMMANDS_LIST_REQUEST";
export const COMMANDS_LIST_SUCCESS = "COMMANDS_LIST_SUCCESS";
export const COMMANDS_LIST_FAIL = "COMMANDS_LIST_FAIL";

//create
export const COMMANDS_CREATE_REQUEST = "COMMANDS_CREATE_REQUEST";
export const COMMANDS_CREATE_SUCCESS = "COMMANDS_CREATE_SUCCESS";
export const COMMANDS_CREATE_FAIL = "COMMANDS_CREATE_FAIL";

//update
export const COMMANDS_UPDATE_REQUEST = "COMMANDS_UPDATE_REQUEST";
export const COMMANDS_UPDATE_SUCCESS = "COMMANDS_UPDATE_SUCCESS";
export const COMMANDS_UPDATE_FAIL = "COMMANDS_UPDATE_FAIL";

//delete
export const COMMANDS_DELETE_REQUEST = "COMMANDS_DELETE_REQUEST";
export const COMMANDS_DELETE_SUCCESS = "COMMANDS_DELETE_SUCCESS";
export const COMMANDS_DELETE_FAIL = "COMMANDS_DELETE_FAIL";
