//list
export const COMMANDS_LIST_REQUEST = "COMMANDS_LIST_REQUEST";
export const COMMANDS_LIST_SUCCESS = "COMMANDS_LIST_SUCCESS";
export const COMMANDS_LIST_FAIL = "COMMANDS_LIST_FAIL";

//create
export const COMMANDS_CREATE_REQUEST = "COMMANDS_CREATE_REQUEST";
export const COMMANDS_CREATE_SUCCESS = "COMMANDS_CREATE_SUCCESS";
export const COMMANDS_CREATE_FAIL = "COMMANDS_CREATE_FAIL";
